# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: highway.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'highway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhighway.proto\"\xd1\x01\n\x06\x44\x65vice\x12\'\n\x0b\x64\x65vice_type\x18\x01 \x01(\x0e\x32\x12.Device.DeviceType\x12)\n\x0cmessage_type\x18\x02 \x01(\x0e\x32\x13.Device.MessageType\x12\n\n\x02id\x18\x03 \x01(\x03\"*\n\nDeviceType\x12\x0e\n\nCONTROLLER\x10\x00\x12\x0c\n\x08RECEIVER\x10\x01\";\n\x0bMessageType\x12\t\n\x05VIDEO\x10\x00\x12\x0b\n\x07\x43ONTROL\x10\x01\x12\n\n\x06REPORT\x10\x02\x12\x08\n\x04\x46ILE\x10\x03\"U\n\x08Register\x12\x17\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\x07.Device\x12!\n\x10subscribe_device\x18\x02 \x01(\x0b\x32\x07.Device\x12\r\n\x05token\x18\x03 \x01(\t\"\x1b\n\x07\x43ontrol\x12\x10\n\x08\x63hannels\x18\x01 \x03(\x03\"\x19\n\x06Report\x12\x0f\n\x07\x62\x61ttery\x18\x01 \x01(\x02\"\'\n\x05Video\x12\x0b\n\x03raw\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\"4\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\x12\x10\n\x08\x63hecksum\x18\x03 \x01(\x03\x42\x1aZ\x18protocol/highway;highwayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'highway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030protocol/highway;highway'
  _globals['_DEVICE']._serialized_start=18
  _globals['_DEVICE']._serialized_end=227
  _globals['_DEVICE_DEVICETYPE']._serialized_start=124
  _globals['_DEVICE_DEVICETYPE']._serialized_end=166
  _globals['_DEVICE_MESSAGETYPE']._serialized_start=168
  _globals['_DEVICE_MESSAGETYPE']._serialized_end=227
  _globals['_REGISTER']._serialized_start=229
  _globals['_REGISTER']._serialized_end=314
  _globals['_CONTROL']._serialized_start=316
  _globals['_CONTROL']._serialized_end=343
  _globals['_REPORT']._serialized_start=345
  _globals['_REPORT']._serialized_end=370
  _globals['_VIDEO']._serialized_start=372
  _globals['_VIDEO']._serialized_end=411
  _globals['_FILE']._serialized_start=413
  _globals['_FILE']._serialized_end=465
# @@protoc_insertion_point(module_scope)
