# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: highway.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'highway.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rhighway.proto\"\xdc\x01\n\x06\x44\x65vice\x12\'\n\x0b\x64\x65vice_type\x18\x01 \x01(\x0e\x32\x12.Device.DeviceType\x12)\n\x0cmessage_type\x18\x02 \x01(\x0e\x32\x13.Device.MessageType\x12\n\n\x02id\x18\x03 \x01(\x03\"*\n\nDeviceType\x12\x0e\n\nCONTROLLER\x10\x00\x12\x0c\n\x08RECEIVER\x10\x01\"F\n\x0bMessageType\x12\t\n\x05VIDEO\x10\x00\x12\x0b\n\x07\x43ONTROL\x10\x01\x12\n\n\x06REPORT\x10\x02\x12\x08\n\x04\x46ILE\x10\x03\x12\t\n\x05\x41UDIO\x10\x04\"h\n\x08Register\x12\x17\n\x06\x64\x65vice\x18\x01 \x01(\x0b\x32\x07.Device\x12!\n\x10subscribe_device\x18\x02 \x01(\x0b\x32\x07.Device\x12\r\n\x05token\x18\x03 \x01(\t\x12\x11\n\tread_only\x18\x04 \x01(\x08\"\x1b\n\x07\x43ontrol\x12\x10\n\x08\x63hannels\x18\x01 \x03(\x05\"\x19\n\x06Report\x12\x0f\n\x07\x62\x61ttery\x18\x01 \x01(\x02\"8\n\x05Video\x12\x0b\n\x03raw\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ounter\x18\x03 \x01(\x04\"~\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x06offset\x18\x02 \x01(\x04\x12\x12\n\ntotal_size\x18\x03 \x01(\x04\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\x0c\x12\x10\n\x08\x63hecksum\x18\x05 \x01(\r\x12\x10\n\x08\x62lock_id\x18\x06 \x01(\r\x12\x12\n\nlast_block\x18\x07 \x01(\x08\"8\n\x05\x41udio\x12\x0b\n\x03raw\x18\x01 \x01(\x0c\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\x12\x0f\n\x07\x63ounter\x18\x03 \x01(\x04\x42\x1aZ\x18protocol/highway;highwayb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'highway_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\030protocol/highway;highway'
  _globals['_DEVICE']._serialized_start=18
  _globals['_DEVICE']._serialized_end=238
  _globals['_DEVICE_DEVICETYPE']._serialized_start=124
  _globals['_DEVICE_DEVICETYPE']._serialized_end=166
  _globals['_DEVICE_MESSAGETYPE']._serialized_start=168
  _globals['_DEVICE_MESSAGETYPE']._serialized_end=238
  _globals['_REGISTER']._serialized_start=240
  _globals['_REGISTER']._serialized_end=344
  _globals['_CONTROL']._serialized_start=346
  _globals['_CONTROL']._serialized_end=373
  _globals['_REPORT']._serialized_start=375
  _globals['_REPORT']._serialized_end=400
  _globals['_VIDEO']._serialized_start=402
  _globals['_VIDEO']._serialized_end=458
  _globals['_FILE']._serialized_start=460
  _globals['_FILE']._serialized_end=586
  _globals['_AUDIO']._serialized_start=588
  _globals['_AUDIO']._serialized_end=644
# @@protoc_insertion_point(module_scope)
