# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ota.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'ota.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tota.proto\"\xeb\x01\n\x15VersionPublishMessage\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x14\n\x0crelease_date\x18\x02 \x01(\x04\x12\x0c\n\x04size\x18\x03 \x01(\x04\x12\x13\n\x0b\x63ontent_md5\x18\x04 \x01(\t\x12\x0b\n\x03url\x18\x05 \x01(\t\x12\x11\n\tchangelog\x18\x06 \x01(\t\x12)\n\x04\x61rch\x18\x07 \x01(\x0e\x32\x1b.VersionPublishMessage.ARCH\"=\n\x04\x41RCH\x12\x07\n\x03\x41LL\x10\x00\x12\t\n\x05\x41RM32\x10\x01\x12\t\n\x05\x41RM64\x10\x02\x12\n\n\x06X86_32\x10\x03\x12\n\n\x06X86_64\x10\x04\x42\x12Z\x10protocol/ota;otab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ota_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\020protocol/ota;ota'
  _globals['_VERSIONPUBLISHMESSAGE']._serialized_start=14
  _globals['_VERSIONPUBLISHMESSAGE']._serialized_end=249
  _globals['_VERSIONPUBLISHMESSAGE_ARCH']._serialized_start=188
  _globals['_VERSIONPUBLISHMESSAGE_ARCH']._serialized_end=249
# @@protoc_insertion_point(module_scope)
