# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: video.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvideo.proto\"w\n\x15VideoAttributeMessage\x12\r\n\x05width\x18\x01 \x01(\x04\x12\x0e\n\x06height\x18\x02 \x01(\x04\x12\x10\n\x08max_rate\x18\x03 \x01(\x04\x12\x12\n\nframe_rate\x18\x04 \x01(\x04\x12\x19\n\x11video_encode_type\x18\x05 \x01(\tB\x16Z\x14protocol/video;videob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'video_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\024protocol/video;video'
  _globals['_VIDEOATTRIBUTEMESSAGE']._serialized_start=15
  _globals['_VIDEOATTRIBUTEMESSAGE']._serialized_end=134
# @@protoc_insertion_point(module_scope)
